// import ThemeProvider from "./context/ThemeProvider";

import ThemeProvider from "@/components/ThemeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <header>
            <h1>this is header</h1>
          </header>

          {children}

          <footer>
            <h1>this is footer</h1>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
