export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
            <h1>this is header</h1>
        </header>
        {children}
        <footer>
            <h1>this is footer</h1>
        </footer>
      </body>
    </html>
  );
}
